feat: support no_std
alloy-rs/trie pull request #2
Opened 2023-12-22 04:36 UTC by yjhmelody

2023-12-24 11:57 UTC, yjhmelody commented
@DaniPopes PTAL

2024-01-12 17:23 UTC, DaniPopes requested changes

2024-01-12 17:23 UTC, DaniPopes commented on Cargo.toml
> +hashbrown = { version = "0.14", features = ["serde", "ahash", "inline-more"] }
serde feature has to be enabled in the `[features]` section

2024-01-12 17:23 UTC, DaniPopes commented on Cargo.toml
>  # serde
```suggestion

# serde
```

2024-01-12 17:23 UTC, DaniPopes commented on src/lib.rs
> +extern crate alloc as std;
Can you remove the alias? I prefer being explicit about `alloc`, plus it doesn't re-export items from `core` like `std` does.

2024-01-12 17:23 UTC, DaniPopes commented on src/lib.rs
> +pub use hashbrown::HashMap;
Should we use `std` hashmap when `std` feature is on?

2024-01-14 11:09 UTC, yjhmelody commented
done

2024-01-24 09:19 UTC, yjhmelody commented
@DaniPopes

2024-01-24 09:34 UTC, DaniPopes approved these changes

2024-01-24 09:34 UTC, merged

2024-01-24 09:53 UTC, DaniPopes commented
Released in [0.2.1](https://crates.io/crates/alloy-trie/0.2.1)